### ISSUE TITLE
Question About Header

### ISSUE THREAD

**Issue by rm3nchaca** [juks/SocketQueue#10]
Hello!
What is the correct form to use the static header? I want to implement something that needs to set up a header for each type of message, ej: 0200: ISO002600005, 0800: ISO002600015....

Thank you! You've done an excelent work! Congratulations!!

**Comment by juks** [comment]
Hi!

Just wondering: what kind of system you need this for?

At the moment, there is useStaticHeader parameter. If adds static header to every single message sent to upstream. Looks like what you requested considers something more complex e.g. useStaticHeaderMap.

If there is some sort of true use case, I can consider an improvement for this.

**Comment by rm3nchaca** [comment]
It's a special requirement for the "logon" message, it is just like any other 0800 but with a different header.
All the headers of 12 bytes, I'm going to check out the code and make tests, at this time I'm receiving a lot of ArrayIndexOutOfBoundsExceptions from my demo jPOS server!

Thanks!

**Comment by juks** [comment]
Do you mean sending message via SocketQueue leads to an error? If so, I suggest using --vv and --dangerous keys to see the actual payload. This really helps debugging. Also you can tweak the acual message saved in a file to the state where it does not lead to exception, then see where the problem is.

**Comment by rm3nchaca** [comment]
Thank you very much!
