### ISSUE TITLE
Sending raw message using HTTP

### ISSUE THREAD

**Issue by kahwooi** [juks/SocketQueue#2]
Can I send raw ISO 8583 message example, 02005000000000000000165419120070537139000000005500, using HTTP instead of upstream?

I saw this on the feature list: Supports both binary ISO-8583 and JSON over HTTP operation modes at the same time, do you have a sample code?

**Comment by juks** [comment]
No, the moment you can't. But it sounds to be a good idea! Will implement
it shrortly.

Can I send raw ISO 8583 message example,
02005000000000000000165419120070537139000000005500,
using HTTP instead of upstream?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/juks/SocketQueue/issues/2>, or mute the thread

**Comment by juks** [comment]
Currenly it accepts ony JSON arrays over HTTP. But it won't take long to implement

**Comment by juks** [comment]
Please update master and check the new /raw url for HTTP:

curl -H "Content-Type: text/plain" -X POST -d '303830302220010000c00000303030303030303630373136313730303132333435363030303030313233343536313233353637383930313234353637' http://localhost:2015/raw

Note it all comes as HEX, not only the binary mask. This is a safe and universal way.

Given example goes as:

     Message Type Indicator [0].......................0800
     Bitmap [1].......................................2220010000800000
     Processing Code [3]..............................990000
     Transmission Date and Time [7]...................0830203545
     System Trace Audit Number [11]...................000001
     Function Code [24]...............................831
     Card Acceptor Terminal Identification [41].......00000001

**Comment by kahwooi** [comment]
Thanks. Your work is awesome. I will explore your gateway more on the integration with bank host.

**Comment by juks** [comment]
Your feedback is always welcomed!
