### ISSUE TITLE
Solving queue conflict

### ISSUE THREAD

**Issue by sintyasin** [juks/SocketQueue#25]
Hello,
i want to send a reversal message 3 times with the exactly same value for every bit, but i got
"**Queue warning: solving queue conflict with 2 pretenders [success]**"
How can i send it without changing any bit in the message im going to send ?

Thank you in advance

**Comment by juks** [comment]
Hi! Queue conflict is detected each time when there are two POS active (who already sent their transactions) clients with same identity waiting for the response.

In your case this might be due to the fact that you have repeated the messages with the same fields before the previous senders left the queue.

Looks like you have solved this already.
