### ISSUE TITLE
Send mesage to external upstream without httpclient

### ISSUE THREAD

**Issue by noecodjo** [juks/SocketQueue#31]
Hi Igor,
Hope you're doing well.
i use SQ now it's really amazing. Thanks
How  can i send a message to an external upstream server without a client connect.
For example i use SQ to connect to a upstream server.  In specs of this server.. at every connection the upstream server must send to me (here SQ) a 0800 message and i should response automaticaly after make some verification by 0810
Actually when i receive the request 0800 from upstream , SQ log error as ISO host send data with no client.
The concerned upstream server connection specifications describe:
1.	Socket must send 0800 to upstream server
2.	upstream server response 0810 and automatically send 0800 with an additionnal data (DE48) 
3.	SQ must verify the value of the additionnal data (DE48) and send a 0810 as response with responseCode 0 and must send automatically new 0800
4.	After this exchange done correctly , the upstream server it ready to receive and authorize transactions request from SQ client
Can you Assist please

**Comment by shoaibjdev** [comment]
You can specify this under queueMessageKeyFields (default: '11,41'), so you can remove 41 while starting up SQ as below

**Example** - 
node socketQueue.js --upstreamHost=X.X.X.X --upstreamPort=54321 --listenPort=2100 --listenHttpPort=2110 --vv --logFile=log.txt **--queueMessageKeyFields=false**

Or, Alternatively you could start SQ specifying queueLockTerminal=false so that SQ queues doesn't lock to a terminal.

**Example** -
node socketQueue.js --upstreamHost=X.X.X.X --upstreamPort=54321 --listenPort=2100 --listenHttpPort=2110 --vv --logFile=log.txt **--queueLockTerminal=false**

**Comment by noecodjo** [comment]
Hi shoaibjdev ,
Thanks for your revert.
About the TID i remove from parameter.js and i just let DE11 (Stan) , waiting to create a logic to ignore this DE for network messages.
My real request it's looking for kind of logic that's automatically send a 0800 request when SQ connected to the upstream and some others message for authentication with the upstream server befor Http client or any SQ client make payment auth request

**Comment by juks** [comment]
Hi!

There is an "Upstream Echo" event: https://github.com/juks/SocketQueue/blob/1b172de810bb928516b511b4fe81b0ae7e0751ac/lib/iso8583/lib/logic/smartVista.js#L103

It is called every time upstream send a 0800 packet to SQ: https://github.com/juks/SocketQueue/blob/1b172de810bb928516b511b4fe81b0ae7e0751ac/lib/socketServer/lib/upstream.js#L253

The thing is you can always tell if the 0800 message is addressed to SQ since it is not a response but a request. How would you like to know if 0810 message does not belong to any client?

Do you mean SQ should own it's own terminal number?

There is a method that is called right after SQ connects to an upstream: https://github.com/juks/SocketQueue/blob/1b172de810bb928516b511b4fe81b0ae7e0751ac/lib/socketServer/lib/upstream.js#L123.

You can add your own code that sends a message to the upstream. But still the question will be: how to process the upstream response in a proper way

**Comment by juks** [comment]
To send a 0800 packet to an upstream every 5 minutes you need to set up a javascript timer.

**Comment by noecodjo** [comment]
Get it.
below code:
```javascript
var echoTestTimout = 300000;
 if (typeof parent.logic.replyUpstreamEcho === 'function') {
           var rp = parent.logic.replyUpstreamEcho(p);
            setTimeout(function() { 
                 dd('Sent echo test request to Upstream ..../5min' , 'verbose');
            this.write(rp.getMessage({
              staticHeader: global.c['useStaticHeader'],
              lengthHeader: global.c['useLengthHeader']
            }));
            }.bind(this)
              , echoTestTimout);```


Thanks for your help. Really appreciate
